(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(package-initialize)
(require 'init-melpa)
(require 'init-usepackage)
